-- AlterTable
ALTER TABLE "Record" ADD COLUMN "kospiAccVolume" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Record" ADD COLUMN "kospiAccAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Record" ADD COLUMN "kosdaqAccVolume" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Record" ADD COLUMN "kosdaqAccAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
